### ISSUE TITLE
Link new CommitteeMembers to respective FacultyMember

### ISSUE THREAD

**Issue by Smullz622** [psu-libraries/etda_workflow#654]
When a Committee Member is added, we need to add that information to the Faculty Member table as well

**Comment by ajkiessl** [comment]
Or link them to an existing Faculty Member.

Alternatively, we could just have the `faculty_member_migration` task run daily (or even weekly) to do the linking.  This might be a better solution since the linking code uses LDAP and could cause some latency for users.  The FacultyMember table is just used to populate the committee member dashboard (https://submit-etda.libraries.psu.edu/committee_member_dashboard), so it doesn't need to be real-time update to date.

**Comment by Smullz622** [comment]
looks like this was already handled here: https://github.com/psu-libraries/etda-config/pull/67
